on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

name: Release and publish package

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/certbot-dns-local
    permissions:
      id-token: write  # Permission is mandatory for trusted publishing
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Automated release of ${{ github.ref }}
        draft: false
        prerelease: false
        body: This is an automated build of commit ${{ github.ref }}.
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1